### PR TITLE
IntersectUsing() new function

### PR DESCRIPTION
**Pull request by AlessandroLorenzi**
---
This change is [Reviewable](https://reviewable.io/reviews/elliotchance/pie/161)

### CODE REVIEW

**Comment by AlessandroLorenzi** [comment]
refs: #72

**Comment by elliotchance** [comment]
Please fix the merge conflict before I review.

**Comment by AlessandroLorenzi** [comment]
hi @elliotchance , what you think about a solution like this?

too overcomplicated?

```go
package functions

// IntersectUsing returns items that exist in all lists, using equals function
//
// It returns slice without any duplicates.
// If zero slice arguments are provided, then nil is returned.
func (ss SliceType) IntersectUsing(equals func(ElementType, ElementType) (bool, interface{}), slices ...SliceType) []interface{} {
	if slices == nil {
		return nil
	}

	found := map[interface{}]int{}

	for _, e1 := range ss {
		for _, s2 := range slices {
			foundInSlice := false
			for _, e2 := range s2 {
				chekFound, checkValue := equals(e1, e2)
				if chekFound {
					found[checkValue]++
					foundInSlice = true
					break // if found the element don't check other elements in this slice
				}
			}
			if !foundInSlice {
				break // if not found in this slice don't check other slices
			}
		}
	}
	ss2 := []interface{}{}

	for value, count := range found {
		if count == len(slices) {
			ss2 = append(ss2, value)
		}
	}
	return ss2
}
```

**Comment by AlessandroLorenzi** [comment]
I'll restart this function from zero

**Pull request closed without merging**
