### PR TITLE
Mode implementation

### PR DESCRIPTION
**Pull request by DylanMeeus**
See #68

---
This change is [Reviewable](https://reviewable.io/reviews/elliotchance/pie/142)

### CODE REVIEW

**Comment by DylanMeeus** [comment]
travis keeps failing either on `go generate` or on `gofmt`.
I notice that go generate does not generate correct code for gofmt in this instance. I suspect that to be the issue with the travis builds here. (either the formatting is wrong or the generate looks out of sync). I'll take a look at this later unless you see an obvious mistake :)

**Comment by DylanMeeus** [comment]
I ran gofmt on all files before generating

**Comment by DylanMeeus** [comment]
I run `gofmt -w .`, which formats the files. Then I run `go generate` and the formatting is gone again. So one of them always seems to be out of sync :confused:

**Comment by elliotchance** [comment]
@DylanMeeus the command you are using is only formatting one package: `github.com/elliotchance/pie`. However, the package that needs to be formatted is `github.com/elliotchance/pie/pie`.

You should use this for all packages:

```bash
go fmt ./...
```

**Comment by DylanMeeus** [comment]
Hey Elliot, my understanding was that `gofmt -w .` would recursively format everything down from the current repository. I'll try that out tonight ;-)

**Comment by DylanMeeus** [comment]
@elliotchance running `go fmt ./...` has the same result as `gofmt -w .`. So running `go fmt ./...` at root changes the files, then I regenerate them and they are different once again. Any idea why the generator does not format correctly?

**Comment by elliotchance** [comment]
@DylanMeeus you may need to be careful of the order so that you don't replace the formatting changes if you immediately run `go generate` after `go fmt`. Also check that you are running Go 1.12 as they do make slight changes to formatting through versions.

**Comment by DylanMeeus** [comment]
issue persists (code is committed after formatting now) with go `1.12.4 linux/amd64`.

**Pull request merged**
