### PR TITLE
implement pop func

### PR DESCRIPTION
**Pull request by hiepndd**
This change is [Reviewable](https://reviewable.io/reviews/elliotchance/pie/114)

### CODE REVIEW

**Comment by hiepndd** [comment]
Hi @elliotchance,
Thanks and `Why can't this work for all slices?` what do you mean? 🤔

**Comment by elliotchance** [comment]
@hiepndd still waiting on merge conflicts before this can be merged.

**Comment by hiepndd** [comment]
@elliotchance  Totaly forget it. I'll do it in tomorrow. Anw sorry about that, I quite busy

**Comment by elliotchance** [comment]
I am closing this because it has already been resolved with #159.

**Pull request closed without merging**
