### PR TITLE
implement shuffle function

### PR DESCRIPTION
**Pull request by hiepndd**
This change is [Reviewable](https://reviewable.io/reviews/elliotchance/pie/58)

### CODE REVIEW

**Comment by zhiburt** [comment]
Hello

I'm not sure but I consider you should use [rand.Seed()](https://golang.org/pkg/math/rand/#Seed) in your function

and I've just come across on excellent function [Shuffle](https://golang.org/pkg/math/rand/#Shuffle) from standard library

**Comment by hiepndd** [comment]
Hi @zhiburt ,
My func based on `Fisher–Yates` algorithm and since go1.10, this is available at math/rand.Shuffle. So they are doing the same.
Anw thanks for your comment.

**Comment by hiepndd** [comment]
Hi @elliotchance,  
So you accepted the other function?. Do I need to change it? and re-create a PR?

**Comment by zhiburt** [comment]
I'm sorry for that @hiepndd. I've only tried to help. I didn't know how to change your func fast so I opened new PR.

Faithfully, That's my fault

**Pull request closed without merging**
