### PR TITLE
Reorganize project directory

### LINKED ISSUE #95: Reorganize project directory and update contribution instructions
Reorganize the project directory using https://github.com/golang-standards/project-layout as a guide.

### PR DESCRIPTION
**Pull request by samlitowitz**
Resolves #95

---
This change is [Reviewable](https://reviewable.io/reviews/elliotchance/pie/96)

### CODE REVIEW

**Comment by samlitowitz** [comment]
What you like about the current structure @zhiburt?

**Comment by zhiburt** [comment]
> What you like about the current structure @zhiburt?

At least, name of package functions more understandable for me then templates).
As for PR, I know that many projects support this folder structure style, and it may be more simplier to support it too, because lots of people know about that something.
I've only wanted to offer to rename package 'templates', but I can mistaken.

**Comment by DylanMeeus** [comment]
A good project structure is one that is _clear_ in my opinion. 
The current structure is clear. Even though I always like to adhere to standards, they are there as a guideline and not as a rule. 

My 2c is that we should not change the current structure, I think anybody can navigate the current structure with ease.

**Comment by elliotchance** [comment]
I've had some time to think about this now. This is not a change I want for the project.

While it's a good idea to follow a guideline, that documentation states that following it would be overkill for small projects. Pie is a small project that I doubt will go any further past its current complexity.

**Pull request closed without merging**
