### PR TITLE
Intersect

### LINKED ISSUE #71: Intersect()
Returns items that exist in both lists.

### PR DESCRIPTION
**Pull request by zhiburt**
As for signature, ```
func (ss SliceType) Intersect(slices ...SliceType) (ss2 SliceType)```
I've decided to do that couse it can be useful immediately intersect several slices.
In cases like this and many others.
```
 var userInterests = Strings{"Football", "Volleyball"}
 theSameInterests :=  userInterests.Intersect(friendsInterests...)
 ...

```

As for realisation, I wonder, should I have been able to use map for it?
That closes #71 

---
This change is [Reviewable](https://reviewable.io/reviews/elliotchance/pie/94)

### CODE REVIEW

**Comment by Deleplace** [comment]
The README line says O(n log n), but I strongly suspect the implementation is O(n^2)...

@zhiburt Yes using maps would be helpful to reduce the complexity to O(n). However, big-O doesn't always tell the whole story, and we would need benchmarks to know which implementation is faster for small and medium values of n.

**Comment by zhiburt** [comment]
> The README line says O(n log n), but I strongly suspect the implementation is O(n^2)...
> 
> @zhiburt Yes using maps would be helpful to reduce the complexity to O(n). However, big-O doesn't always tell the whole story, and we would need benchmarks to know which implementation is faster for small and medium values of n.

@Deleplace could you help me?
I've added function with implementation with map, and my benchmarks show it as better way (I'm not sure that this is a representative benchmark)
But I realise that the solution doesn't have O(n)
```

goos: linux
goarch: amd64
pkg: github.com/elliotchance/pie/pie
BenchmarkStrings_SmallSet_Intersect-4            2000000               970 ns/op             240 B/op          9 allocs/op
BenchmarkStrings_SmallSet_Intersect2-4           2000000              1101 ns/op             520 B/op         11 allocs/op
BenchmarkStrings_LargeSet_Intersect-4                  2         521059577 ns/op         2999184 B/op        434 allocs/op
BenchmarkStrings_LargeSet_Intersect2-4               300           4915841 ns/op         2178187 B/op        449 allocs/op
PASS
Tests: 517, Assertions: 1480, Time: 12.238162996s


```

**Comment by Deleplace** [comment]
Well done for the `LargeSet`improvement! What makes you think that `Intersect2` is not O(n)?
Informally, n is the total number of elements in receiver+arguments.

Also we should say in the comments that Intersect has the side effect of removing any duplicates existing in the receiver.

**Comment by zhiburt** [comment]
As for complexity this is [here](https://github.com/elliotchance/pie/pull/94#issuecomment-489432020).
That improvement must change performance in better way

**Pull request merged**
